import { notFound } from 'next/navigation'
import UseCasePage from '@/components/UseCasePage'

const cases={
  'tuition-fee-reminders':{title:'Tuition Fee Reminder App for Tutors',description:'Track monthly tuition fees and prepare polite WhatsApp payment reminders with KhataPing.',eyebrow:'For tutors & coaching',heading:'Tuition fee reminders without maintaining another notebook.',body:'Keep every student’s monthly fee date, amount and status in one place, then follow up only when attention is needed.',pains:['Monthly fees arrive on different dates.','Parent follow-ups get buried in WhatsApp chats.','A spreadsheet tells you the amount, not who needs a nudge today.'],features:['Add the student or parent and monthly fee.','See upcoming, due and overdue fees automatically.','Use a polite WhatsApp-ready message with your UPI details.'],keyword:'A simple tuition fee reminder app for Indian tutors.'},
  'pg-rent-reminders':{title:'PG Rent & Monthly Dues Reminder App',description:'Track PG rent, mess dues and recurring tenant payments with KhataPing.',eyebrow:'For PG owners',heading:'Know which room paid rent—before you start asking around.',body:'Track recurring PG rent and related monthly dues, without mixing payment memory with dozens of tenant chats.',pains:['Residents pay on different days and through different UPI apps.','Rent, mess and other recurring dues are easy to mix up.','Manual follow-ups take time every month.'],features:['Add each resident and recurring amount.','See rent that is paid, pending or overdue.','Send a clear reminder containing the amount and payment route.'],keyword:'PG rent reminders built for small Indian operators.'},
  'gym-payment-reminders':{title:'Gym Membership Payment Reminder App',description:'Track gym membership renewal dues and follow up with members using KhataPing.',eyebrow:'For gyms & studios',heading:'Membership renewals should not disappear between workouts.',body:'Keep upcoming renewals visible so staff can follow up at the right time without searching old receipts or chats.',pains:['Different members renew on different dates.','Expired memberships are easy to miss during busy hours.','Staff repeatedly type the same reminder message.'],features:['Record member, amount and renewal frequency.','Review upcoming and overdue renewals in one list.','Use a consistent reminder and direct UPI payment route.'],keyword:'A lightweight gym fee and membership reminder app.'},
  'freelancer-payment-reminders':{title:'Freelancer Payment Reminder App India',description:'Track recurring retainers and client payment follow-ups with KhataPing.',eyebrow:'For freelancers',heading:'Follow up on retainers without sounding like a collection department.',body:'Track recurring client dues and keep a professional reminder ready when an invoice or retainer date arrives.',pains:['Client work and payment follow-up live in the same chat.','It is easy to postpone an awkward reminder.','Recurring retainers still require manual monthly tracking.'],features:['Record the client, retainer amount and monthly date.','See outstanding client dues in a single dashboard.','Prepare a concise professional reminder with payment information.'],keyword:'Simple freelancer payment reminders for Indian independent professionals.'},
  'small-business-dues':{title:'Small Business Recurring Dues Tracker India',description:'Track recurring service dues and customer payment reminders for Indian small businesses.',eyebrow:'For local services',heading:'Recurring customers are great. Recurring chasing is not.',body:'Use KhataPing when your service is simple, your customers repeat, and you do not need an enterprise accounting system to remember who owes what.',pains:['Payment status is scattered across calls, chats and notes.','Broad accounting products can be more than the workflow needs.','Small missed dues add up over time.'],features:['Add the customer and repeating amount.','Prioritize the dues that actually need attention.','Keep follow-ups consistent and payments direct to you.'],keyword:'Recurring dues tracking for Indian small service businesses.'}
}

export function generateStaticParams(){return Object.keys(cases).map(slug=>({slug}))}
export async function generateMetadata({params}){const {slug}=await params;const c=cases[slug];if(!c)return {};return {title:c.title,description:c.description}}
export default async function Page({params}){const {slug}=await params;const c=cases[slug];if(!c)notFound();return <UseCasePage eyebrow={c.eyebrow} title={c.heading} description={c.body} pains={c.pains} features={c.features} keyword={c.keyword}/>}
